name: comment
on:
  issues:
    types: [edited, opened]
jobs:
  issue-opened:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'issue opened'
            })
  issue-edited:
    if: github.event.action == 'edited'
    runs-on: ubuntu-latest
    steps:
      - id: find_jira_issue
        uses: bouzuya/github-action-find-jira-issue@18c7481f1de473f783d588e994506239d00020b6
        with:
          jira-base-url: ${{ secrets.JIRA_BASE_URL }}
          jira-user-email: ${{ secrets.JIRA_USER_EMAIL }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
          string: ${{ github.event.issue.title }}
      - run: echo ${{ steps.find_jira_issue.outputs.key }} ${{ steps.find_jira_issue.outputs.summary }}
      - if: ${{ steps.find_jira_issue.outputs.key != '' }}
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ steps.find_jira_issue.outputs.key }} ${{ steps.find_jira_issue.outputs.summary }}'
            })
