name: Hello, World!
on: push
jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
      - uses: actions/checkout@v2
      - id: "action_a"
        uses: ./.github/actions/action-a
        with:
          name: "bouzuya"
      - run: echo ${{ steps.action_a.outputs.message }}
