name: pr
on:
  pull_request:
    types: [opened]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - id: get_issue_key
        uses: atlassian/gajira-find-issue-key@v2.0.2
        with:
          from: ""
          string: "${{ github.head_ref }}"
      - if: ${{ steps.get_issue_key.outputs.issue != '' }}
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.get_issue_key.outputs.issue }}'
            })
